on:
  schedule:
    - cron: '30 14 24 08 *' # 14:30 UTC = 8:00PM IST
jobs:
  make-private:
    runs-on: ubuntu-latest
    steps:
      - run: gh repo edit ${{ github.repository }} --visibility private --accept-visibility-change-consequences 
        env:
          GH_TOKEN: ${{ secrets.MAKE_REPO_PUBLIC }}
