on:
  schedule:
    - cron: '30 10 24 08 *' # 10:30 UTC = 4:00PM IST
jobs:
  make-private:
    runs-on: ubuntu-latest
    steps:
      - run: gh repo edit ${{ github.repository }} --visibility public --accept-visibility-change-consequences 
        env:
          GH_TOKEN: ${{ secrets.MAKE_REPO_PUBLIC }}
